version: "3.9"

services:
  redis_server:
    image: redis
    command: redis-server
    ports:
      - "6378:6379"
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - redis_server
    depends_on:
      - redis_server